## 🎯 Exercícios 🎯 <a class="anchor" id="cinco"></a>

- Crie duas series aleatorias com 30 numeros, no intervalo 20 a 50 cada  ds1 ds2
- Crie uma nova serie com o nome g_than com a comparação entre a s1 e a s2 
- Crie uma nova serie com o nome ds_sum com a soma das duas series 
- Apresente o desvio padrão da serie ds_sum
- Crie uma nova serie com 30 strings de 5 caracteres aleatorios (Dica. random.choice + string.ascii_lowercase)
- Crie uma lista com todas as series criadas 
- Crie um dataframe com as suas series (Dica. pd.concat())
- Coloque o nome de cada serie no novo dataframe (Dica .rename)

In [17]:
import random 
import string

In [18]:
ds1 = pd.Series(np.random.randint(20,51,size = 8))
ds2 = pd.Series(np.random.randint(20,51,size = 8))

g_than = pd.Series(ds1 > ds2)

ds_sum = pd.Series(ds1 +ds2)

ds_sum.std()

# string_serie = pd.Series(random.choice(string.ascii_lowercase) for x in range(5) for j in range(5))

# str_list = []
# for i in range(8):
#     str = ""
#     for j in range(5):
#         str+= random.choice(string.ascii_lowercase)
#     str_list.append(str)

str_list = []
for i in range(8):
    str_list.append((''.join((random.choice(string.ascii_lowercase)) for x in range(5))))
string_serie = pd.Series(str_list)


lista =[ds1,ds2,g_than,ds_sum,string_serie]

df = pd.concat(lista,axis = 1)

df.rename(columns={0:"ds1",1:"ds2",2:"g_than",3:"ds_sum",4:"string_serie"})

   ds1  ds2  g_than  ds_sum string_serie
0   31   47   False      78        zcayu
1   33   43   False      76        mbnpf
2   46   46   False      92        koxpz
3   35   47   False      82        paeks
4   38   32    True      70        ddrjb
5   43   27    True      70        facxa
6   45   42    True      87        ccbjt
7   28   36   False      64        atmux



Ver o dicionario sobre o arquivo 
https://dados.gov.br/dataset/preco-de-medicamentos-no-brasil-consumidor

Prestar atenção no encoding ('iso-8859-15','utf-8','ascii') Googleit


- 1.Carregar TA_PRECO_MEDICAMENTO.csv


- 2.Revisar os dados (info, columns, head, tail...)


- 3.Subset da Classe Terapeutica = N2C9 - TODOS AS OUTRAS PREPARAÇÕES ANTIENXAQUECOSAS


- 4.Fazer Transformaçoes da coluna de PMC12% para float

- 5.Preço Máximo, Minimo e Mediaao Consumidor %12 da Classse Terapeutica = N2C9 - TODOS AS OUTRAS PREPARAÇÕES ANTIENXAQUECOSAS e trazer a a linha com todas as infos do df


- 6.Coletar 3 tipos de informações relevantes do dataset inteiro
    - 6a Quantidade de Remedios por tipo tarja DICA (groupby)

    - 6b Os 10 laboratorios com mais remedios em ordem decrescente DICA(sortby)
    
    - 6c Faça um groupby Substância e tire um aggregate da coluna PMC 12% com min, max e mean
    
    - 6d Informação que vocês acharem relevante

In [14]:
import pandas as pd

df = pd.read_csv(r'C:/Users/Fernanda/Documents/Top Coders/top-coders-data-science/Modulo III/Exercicios/Bases  Aula 02/TA_PRECO_MEDICAMENTO.csv', sep = ";",encoding = 'latin-1', low_memory=False, decimal = ",")

In [ ]:
df.info()

In [ ]:
df.head(4)

In [ ]:
df.tail()

In [ ]:
df.columns

In [28]:
df_enx = df[df["CLASSE TERAPÊUTICA"] == "N2C9 - TODOS AS OUTRAS PREPARAÇÕES ANTIENXAQUECOSAS"].copy()

In [ ]:
df['PMC 12%'] = df['PMC 12%'].astype('float') 


df['PMC 12%']

In [ ]:
lista = [df[df['CLASSE TERAPÊUTICA'] =='N2C9 - TODOS AS OUTRAS PREPARAÇÕES ANTIENXAQUECOSAS'].mean(),df[df['CLASSE TERAPÊUTICA'] =='N2C9 - TODOS AS OUTRAS PREPARAÇÕES ANTIENXAQUECOSAS'].max(),df[df['CLASSE TERAPÊUTICA'] =='N2C9 - TODOS AS OUTRAS PREPARAÇÕES ANTIENXAQUECOSAS'].min()]
df_medidas = pd.concat(lista, axis = 1)
display(df_medidas)

In [36]:
media = df_enx['PMC 12%'].mean()
max = df_enx['PMC 12%'].max()
min = df_enx['PMC 12%'].min()

display(df_enx[df_enx['PMC 12%'] == media])
display(df_enx[df_enx['PMC 12%'] ==max])
display(df_enx[df_enx['PMC 12%'] ==min])

Empty DataFrame
Columns: [SUBSTÂNCIA, CNPJ, LABORATÓRIO, CÓDIGO GGREM, REGISTRO, EAN 1, EAN 2, EAN 3, PRODUTO, APRESENTAÇÃO, CLASSE TERAPÊUTICA, TIPO DE PRODUTO (STATUS DO PRODUTO), REGIME DE PREÇO, PF Sem Impostos, PF 0%, PF 12%, PF 17%, PF 17% ALC, PF 17,5%, PF 17,5% ALC, PF 18%, PF 18% ALC, PF 20%, PMC 0%, PMC 12%, PMC 17%, PMC 17% ALC, PMC 17,5%, PMC 17,5% ALC, PMC 18%, PMC 18% ALC, PMC 20%, RESTRIÇÃO HOSPITALAR, CAP, CONFAZ 87, ICMS 0%, ANÁLISE RECURSAL, LISTA DE CONCESSÃO DE CRÉDITO TRIBUTÁRIO (PIS/COFINS), COMERCIALIZAÇÃO 2020, TARJA]
Index: []

[0 rows x 40 columns]

,SUBSTÂNCIA,CNPJ,LABORATÓRIO,CÓDIGO GGREM,REGISTRO,EAN 1,EAN 2,EAN 3,PRODUTO,APRESENTAÇÃO,...,PMC 18% ALC,PMC 20%,RESTRIÇÃO HOSPITALAR,CAP,CONFAZ 87,ICMS 0%,ANÁLISE RECURSAL,LISTA DE CONCESSÃO DE CRÉDITO TRIBUTÁRIO (PIS/COFINS),COMERCIALIZAÇÃO 2020,TARJA
13752,GALCANEZUMABE,43.940.618/0001-44,ELI LILLY DO BRASIL LTDA,507620040020807,1126002000038,7896382708565,-,-,EMGALITY,120 MG/ML SOL INJ CT 3 SER PREENC VD TRANS X 1...,...,8181.25,9327.77,Não,Não,Não,Não,NaN,Negativa,Não,Tarja -(*)
13755,GALCANEZUMABE,43.940.618/0001-44,ELI LILLY DO BRASIL LTDA,507620040021307,1126002000062,7896382708596,-,-,EMGALITY,120 MG/ML SOL INJ CT 3 SER PREENC VD TRANS X 1 ML,...,8181.25,9327.77,Não,Não,Não,Não,NaN,Negativa,Não,Tarja -(*)

,SUBSTÂNCIA,CNPJ,LABORATÓRIO,CÓDIGO GGREM,REGISTRO,EAN 1,EAN 2,EAN 3,PRODUTO,APRESENTAÇÃO,...,PMC 18% ALC,PMC 20%,RESTRIÇÃO HOSPITALAR,CAP,CONFAZ 87,ICMS 0%,ANÁLISE RECURSAL,LISTA DE CONCESSÃO DE CRÉDITO TRIBUTÁRIO (PIS/COFINS),COMERCIALIZAÇÃO 2020,TARJA
24505,PARACETAMOL;CAFEÍNA;ÁCIDO ACETILSALICÍLICO,61.082.426/0002-07,COSMED INDUSTRIA DE COSMETICOS E MEDICAMENTOS ...,540921050047307,1781701230033,7896094920910,-,-,DORIL ENXAQUECA,250 MG + 250 MG + 65 MG COM REV CT BL AL AL X 8,...,14.16,16.13,Não,Não,Não,Não,NaN,Negativa,Não,Tarja Venda Livre/Sem Tarja (*)

In [37]:
df.groupby(by=['TARJA']).size().reset_index(name = 'counts')

                             TARJA  counts
0                           - (*)       49
1                     Tarja  Preta     173
2                  Tarja  Vermelha    7132
3                       Tarja -(*)    1571
4                   Tarja Preta(*)     379
5                Tarja Venda Livre    1299
6  Tarja Venda Livre/Sem Tarja (*)    1551
7               Tarja Vermelha (*)    3878
8                Tarja Vermelha(*)   10278

In [39]:
df.groupby(by=['LABORATÓRIO']).size().reset_index(name = 'counts').sort_values(by=['counts'],ascending=False).head(10)

                                         LABORATÓRIO  counts
78                                           EMS S/A    1476
4                ACHÉ LABORATÓRIOS FARMACÊUTICOS S.A    1122
219                       PRATI DONADUZZI & CIA LTDA     883
172       LEGRAND PHARMA INDÚSTRIA FARMACÊUTICA LTDA     875
104                         GERMED FARMACEUTICA LTDA     870
231                 SANOFI MEDLEY FARMACÊUTICA LTDA.     864
81                       EUROFARMA LABORATÓRIOS S.A.     779
201                    NOVA QUIMICA FARMACÊUTICA S/A     755
102                GEOLAB INDÚSTRIA FARMACÊUTICA S/A     736
66   CRISTÁLIA PRODUTOS QUÍMICOS FARMACÊUTICOS LTDA.     713